# -*- coding: utf-8 -*-
"""mailPriceAlert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcLZGbsp6Jd30bUYBExVARSMb38mJUYU
"""

from bs4 import BeautifulSoup
import requests
import time
import smtplib
import ssl
import json
from email.mime.text import MIMEText as MT
from email.mime.multipart import MIMEMultipart as MM
import websockets
import asyncio




receiver = 'anyMail.com'
sender = 'yourMail.com'
sender_password = ''

def send_email(sender, receiver, sender_password, text_price):
  msg = MM()
  msg['Subject'] = "New Crypto Price Alert !"
  msg['From'] = sender
  msg['To'] = receiver

  HTML = """
    <html>
      <body>
        <h1>New Crypto Price Alert !</h1>
        <h2>"""+text_price+"""</h2>
      </body>
    </html>
    """
  MTObj = MT(HTML, "html")
  msg.attach(MTObj)
  
  SSL_context = ssl.create_default_context()

  server = smtplib.SMTP_SSL(host="smtp.gmail.com", port=465, context=SSL_context)
  server.login(sender, sender_password)
  server.sendmail(sender, receiver, msg.as_string())

coin = ""
alarm_price = ""

async def coin_price_1(coin):
    url = "wss://stream.binance.com:9443/ws/{}@miniTicker".format(coin)

    async with websockets.connect(url) as ws:
        msg = await ws.recv()
        return msg

async def coin_price_loop(coin):
    url = "wss://stream.binance.com:9443/ws/{}@miniTicker".format(coin)

    async with websockets.connect(url) as ws:
        while True:
            msg = await ws.recv()
            return msg


def taking_price(coin):
	data = asyncio.get_event_loop().run_until_complete(coin_price_loop(coin))
	price = json.loads(data)
	price = price["c"]
	price = float(price)

def send_alert(coin):
	
	
	data = asyncio.get_event_loop().run_until_complete(coin_price_1(coin))
	price = json.loads(data)
	price = price["c"]
	price = float(price)


	while price <= alarm_price:
		taking_price(coin)

		if price >= alarm_price:
			print(coin.capitalize()+' price: ', price)
			price_text = coin.capitalize()+' is '+str(price)
			send_email(sender, receiver, sender_password, price_text)
	
	while price >= alarm_price:
		taking_price(coin)
		
		if price <= alarm_price:
			print(coin.capitalize()+' price: ', price)
			price_text = coin.capitalize()+' is '+str(price)
			send_email(sender, receiver, sender_password, price_text)

while True:
  coin = input("Coin: ")
  alarm_price = float(input("Alarm: "))
  
  
  send_alert(coin)

  




# https://accounts.google.com/DisplayUnlockCaptcha hata verdiğinde captcha onayı için buraya gir
